name: Coverage PR Comment

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

          
      - name: Install jacoco2cobertura
        run: |
          pip install jacoco2cobertura

      - name: Convert Jacoco to Cobertura
        run: |
          jacoco2cobertura target/site/jacoco/jacoco.xml \
           --output cobertura.xml

      - name: Generate Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage.xml'
          format: 'cobertura'
          output: 'both'
          badge: true

      - name: Post PR Coverage Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
