name: Coverage PR Comment

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Fetch coverage-data branch
        run: |
          git fetch origin coverage-data
          git checkout origin/coverage-data -- coverage.xml

      - name: Generate Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage.xml'
          format: 'markdown'
          output: 'both'
          badge: true

      - name: Post PR Coverage Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
